- client/src/index.css
Added image under images folder
> Newest background for landing page

- client/src/pages/LandingPage.jsx
Landing page is still in the works, but general responsiveness should be fine for mobile devices. The layout is still yet to be finalized.
> updated: landing page

- client/src/App.jsx
- client/src/components/SignInOutLayout.jsx
- client/src/components/SignUpForm.jsx
- client/src/pages/SignUpPage.jsx
Added files for SignUp (Frontend):
+ SignInOutLayout - reduce redundancy for sign in and out
+ SignUpPage - parent and actual page
+ SignUpForm - child, will contain input fields etc
> added: signup frontend files

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/components/Navbar.jsx
- client/src/components/SignInUpLayout.jsx
- client/src/components/SignUpForm.jsx
- client/src/pages/LandingPage.jsx
- client/src/pages/SignUpPage.jsx
updated:
+ signup page
+ signup layout
+ signup form
+ navbar - now displays different content depending on the page. currently only works for sign up
> updated: signup page & navbar

- client/src/App.jsx
- client/src/components/Navbar.jsx
- client/src/components/SignInForm.jsx
- client/src/pages/SignInPage.jsx
Added:
+ sign in page
+ sign in form - included email validation + hidden password
Updated:
+ sign up - email validation + hidden password
> added: sign in page

- client/src/components/Footer.jsx
Footer updated to new design on Figma
> updated: footer

- client/src/pages/LandingPage.jsx
Updated hero component in landing page:
+ "Get Started" now links to sign up
> updated: landing page hero component "get started"

- client/src/pages/GettingStartedPage.jsx
Updated First SignIn / Getting Started UI. Still subject to change later, just keeping it barebones so we can continue with the connections and such.
> updated: first signin

- client/src/pages/DashboardPage.jsx
Added:
+ hide total balance
+ components are open by default
+ can now have multiple components open at the same time
> added: hide balance and open components by defualt

- client/src/App.jsx
- client/src/components/AddAccount.jsx
- client/src/components/AddBudget.jsx
- client/src/components/HowToBudget.jsx
- client/src/components/ViewAccounts.jsx
- client/src/pages/BudgetsPage.jsx
this branch supposed to be for accounts ra but ako nlng g isa sa pag reformat sa pop up in Add Budgets sa Budgets Page HAJHDJAHJKA if iwork on diff branches mag libog ko :"">> UI needs better work pa huhu but the inputs r pretty much g na
AddBudget.jsx
HowToBudget.jsx
AddAccount.jsx
ViewAccounts.jsx
App.jsx
- here i just removed unnecessary routes since dili na separate page/view ang AddBudgets.jsx and AddAccount.jsx, rather its just a popup in specific pages
> PR to merge component/add-accounts with main 

- client/src/components/HamburgerIcon.jsx
- client/src/components/ViewAccounts.jsx
- client/src/index.css
- client/src/pages/DashboardPage.jsx
- new component for the hamburg
- declared css globally for layout purposes
- imported the new component to dashboard
> PR to merge Component/hamburg-icon branch to main

- client/src/pages/DashboardPage.jsx
updated:
+ font color, weight, and size when user has no data
+ changed Php to ₱
+ added ₱ to hidden balance
> update: default case if no data is available

- client/src/components/TransactionDaily.jsx
> update: changed icon for collapsing component

- client/src/components/transactions/Income.jsx
- server/controllers/transactions/makeIncome.js
update: user can now make income transactions
> PT to merge transaction/income branch

- client/src/components/budgets/AddBudget.jsx
- client/src/components/budgets/BudgetCard.jsx
- client/src/index.css
- client/src/pages/BudgetsPage.jsx
fixed: 
+ overflow issue in budgets when components reached >= a certain amount
+ general conflicting styles
updated:
+ centered no budgets component
+ fixed "Add a Budget" to the bottom right of the screen so user doesn't need to scroll all the way down
Overflow Issue Fixed:
> update: budgets page

- client/src/components/transactions/Expense.jsx
- client/src/components/transactions/Income.jsx
- client/src/components/transactions/TransactionCard.jsx
- client/src/components/transactions/Transfer.jsx
- server/controllers/transactions/makeExpense.js
- server/controllers/transactions/makeTransfer.js
-income
-expense
-transfer
income-green
expense-red
transfer-white
> PR to merge transactions/notes-descrip

- client/src/components/transactions/TransactionDaily.jsx
- client/src/components/transactions/TransactionMonthly.jsx
- client/src/components/transactions/TransactionSingle.jsx
- client/src/components/transactions/TransactionWeekly.jsx
- client/src/pages/TransactionsPage.jsx
added:
+ what account a specific transaction comes from (frontend)
updated:
+ made the styles more uniform. although could definitely make it better, have to push this and move onto the next given the time frame and tasks left
> update: transactions page ui

- client/src/components/categories/Categories.jsx
> fix: overflow issue with categories

- client/src/components/transactions/Expense.jsx
> fixed: overflow issue in AddExpense

- client/src/pages/DashboardPage.jsx
> fix: transaction UI

- client/src/components/categories/Categories.jsx
- client/src/components/categories/CategoryCard.jsx
- server/controllers/categories/deleteCategory.js
user can now create, read, update, delete a category
> PR to merge crud/categories

- client/src/components/budgets/BudgetCard.jsx
- client/src/pages/BudgetsPage.jsx
update: user can now delete budgets
> PT TO MERGE branch feature/delete-budget

- client/src/components/budgets/BudgetCard.jsx
added: frontend for edit but not functional
> PR TO merge branch edit-budgets

- client/src/components/transactions/EditTransaction.jsx
- client/src/components/transactions/TransactionSingle.jsx
added: modal for editing transactions
> PR to merge transaction-modals

- client/src/components/transactions/TransactionDaily.jsx
- client/src/components/transactions/TransactionSingleTransfer.jsx
transfer transactions now have delete button but no functionality yet
> PR to merge Transactions/delete-transfer-transac branch

- client/src/components/transactions/TransactionDaily.jsx
- client/src/components/transactions/TransactionSingle.jsx
fixed: daily amount upon deleting transaction
> PR to merge branch trans/fix-daily-amount
